name: architect-bias
channels:
  - defaults
dependencies:
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - libcxx=10.0.0
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.0.1
  - python=3.7.10
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.35.4
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - antlr4-python3-runtime==4.8
    - boto3==1.17.54
    - botocore==1.20.54
    - cffi==1.14.5
    - chardet==4.0.0
    - click==7.1.2
    - cython==0.29.23
    - dataclasses==0.6
    - datasets==1.5.0
    - dill==0.3.3
    - fairseq==0.10.2
    - filelock==3.0.12
    - fsspec==2021.4.0
    - huggingface-hub==0.0.8
    - hydra-core==1.0.6
    - idna==2.10
    - importlib-metadata==4.0.0
    - importlib-resources==5.1.2
    - jmespath==0.10.0
    - joblib==1.0.1
    - multiprocess==0.70.11.1
    - numpy==1.20.2
    - omegaconf==2.0.6
    - packaging==20.9
    - pandas==1.2.4
    - portalocker==2.0.0
    - protobuf==3.15.8
    - pyarrow==3.0.0
    - pycparser==2.20
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytorch-pretrained-bert==0.6.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - regex==2021.4.4
    - requests==2.25.1
    - s3transfer==0.4.0
    - sacrebleu==1.5.1
    - sacremoses==0.0.45
    - sentencepiece==0.1.95
    - six==1.15.0
    - tensorboardx==2.2
    - tokenizers==0.9.4
    - torch==1.8.1
    - tqdm==4.49.0
    - transformers==4.5.1
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - xxhash==2.0.2
    - zipp==3.4.1

